# file path
file_path: ''
out_dir: './out_dir'
# whether to use lighting and shadows

# number of samples to generate
num_observations: 32
# train or test mode
mode: test

object:
    scale: 100
    center_mode: 'mean'

lighting:
    enable: true
    is_random: true
    # sun light settings
    sun_light:
        rotation_euler_y: 0
        rotation_euler_z: 0
        energy: 5.0
        radius: 0.00686  # default size of sun in Blender
        use_shadow: true
        contact_shadow:
            distance: 2.0
            thickness: 0.2
        cascade_count: 4
        cascade_max_distance: 500
    # ambient light
    ambient_light: [0.2, 0.2, 0.2, 1.0]
            
rendering:
    camera:
        # image resolution
        width: 1024
        height: 1024
        # camera fov
        fov: 0.785  # 45 degrees
    shadow:
        # shadow settings
        cascade_size: "4096"
        use_soft_shadows: true
    ao:
        # ambient occlusion
        enable: true
        distance: 1.0
        use_bounce: false
        use_bent_normals: false
    color_management:
        view_transform: 'Filmic'
        look: 'High Contrast'
